apiVersion: v1
kind: Secret
metadata:
  name: store-platform-secrets
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | quote }}
  WORDPRESS_PASSWORD: {{ .Values.secrets.wordpressPassword | quote }}
  MARIADB_ROOT_PASSWORD: {{ .Values.secrets.mariadbRootPassword | quote }}
  MARIADB_PASSWORD: {{ .Values.secrets.mariadbPassword | quote }}
  DATABASE_URL: "postgresql://user:{{ .Values.secrets.postgresPassword }}@postgres:5432/stores"
