apiVersion: v1
kind: ServiceAccount
metadata:
  name: stores-worker
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: stores-worker-admin
subjects:
  - kind: ServiceAccount
    name: stores-worker
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  selector:
    matchLabels:
      app: worker
  replicas: {{ .Values.worker.replicaCount }}
  template:
    metadata:
      labels:
        app: worker
    spec:
      serviceAccountName: stores-worker
      containers:
      - name: worker
        image: "{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag }}"
        imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: store-platform-secrets
              key: DATABASE_URL
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
        - name: PUBLIC_IP
          value: {{ .Values.publicIp | quote }}
        - name: WORDPRESS_USERNAME
          value: {{ .Values.secrets.wordpressUsername | default "admin" | quote }}
        - name: WORDPRESS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: store-platform-secrets
              key: WORDPRESS_PASSWORD
        - name: WORDPRESS_EMAIL
          value: {{ .Values.secrets.wordpressEmail | default "admin@example.com" | quote }}
        - name: WORDPRESS_PLUGINS
          value: {{ .Values.secrets.wordpressPlugins | default "woocommerce" | quote }}
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: store-platform-secrets
              key: MARIADB_ROOT_PASSWORD
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: store-platform-secrets
              key: MARIADB_PASSWORD
        - name: MARIADB_DATABASE
          value: {{ .Values.secrets.mariadbDatabase | default "bitnami_wordpress" | quote }}
        resources:
          {{- toYaml .Values.worker.resources | nindent 10 }}
---
{{- if .Values.worker.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: worker-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: worker
  minReplicas: {{ .Values.worker.hpa.minReplicas }}
  maxReplicas: {{ .Values.worker.hpa.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.worker.hpa.targetCPUUtilizationPercentage }}
{{- end }}
